# Generated by Django 4.1 on 2022-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientlisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.SmallIntegerField()),
                ('last_bmi_status', models.CharField(choices=[('o', 'Overweight'), ('n', 'Normal'), ('u', 'Underweight')], max_length=17, null=True)),
            ],
        ),
    ]
