# Generated by Django 4.1 on 2022-08-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlisting',
            name='last_bmi_status',
            field=models.CharField(choices=[('o', 'Overweight'), ('norm', 'Normal'), ('u', 'Underweight')], max_length=17, null=True),
        ),
    ]
