# Generated by Django 4.1 on 2022-08-07 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0002_alter_patientlisting_last_bmi_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=34)),
                ('lastname', models.CharField(max_length=34)),
                ('date_of_birth', models.DateField()),
                ('patient_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True)),
                ('age', models.SmallIntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('date_of_registeration', models.DateField()),
                ('registrar', models.CharField(max_length=29)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_Date', models.DateTimeField(default=datetime.datetime.now)),
                ('general_health', models.CharField(choices=[('g', 'Good'), ('p', 'Poor')], max_length=4, null=True)),
                ('comments', models.TextField()),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkup.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=datetime.datetime.now)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checkup.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Patientlisting',
        ),
    ]
