# Generated by Django 4.1 on 2022-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0003_patient_patientvisit_vitals_delete_patientlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='Have_you_ever_been_on_diet',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=15, null=True),
        ),
    ]
