# Generated by Django 4.1 on 2022-08-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0004_patientvisit_have_you_ever_been_on_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='bmi',
        ),
    ]
