# Generated by Django 4.1 on 2022-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0005_remove_vitals_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
