# Generated by Django 4.1 on 2022-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0006_remove_patient_id_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='Have_you_ever_been_on_diet',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='general_health',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor')], max_length=4, null=True),
        ),
    ]
